server:
  port: 31001

spring:
  application:
    name: xuechengzaixian-server-manager-cms
  data:
    mongodb:
      uri: mongodb://localhost
      database: xc_cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0  #检查模板更新延迟时间 为0则当数据模板改变时立即刷新