server:
  port: 31001
spring:
  application:
    name: xuechengzaixian-server-manager-cms
  data:
    mongodb:
      uri: mongodb://localhost
      database: xc_cms
  #      uri: mongodb://114.55.37.2:27017,114.55.37.2:27018,114.55.37.2:27019/xc_cms?slaveOk=true&replicaSet=myrs&write=1&readPreference=secondaryPreferred&connectTimeoutMS=300000
  freemarker:
    cache: false
    settings:
      template_update_delay: 0  #检查模板更新延迟时间 为0则当数据模板改变时立即刷新
  #配置rabbitmq
  rabbitmq:
    addresses: 192.144.198.148:5672
    virtual-host: /
    username: guest
    password: guest
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true                              # 没有路由到的消息不会被自动删除
    listener:
      simple:
        # 配置了手工签收
        acknowledge-mode: manual                    # 手工签收
        concurrency: 1
        max-concurrency: 10
        retry:
          enabled: true                             # 是否支持重试
          max-attempts: 5                           # 最大重试次数
          max-interval: 1200                        # 最大重试时间
  cloud:
    nacos:
      discovery:
        server-addr: 192.144.198.148:8848
  aop:
    auto: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
xuecheng:
  mq:
    #queuename: queue_cms_postpage_01
    # 路由Key为门户站点ID
    routingkey: 5a751fab6abb5044e0d19ea1
    exchangename: ex_routing_cms_postpage
feign:
  hystrix:
    enabled: true

