server:
  port: 31000
spring:
  application:
    name: xuechengzaixian-server-cmsclient
  data:
    mongodb:
      #默认端口为27017
      uri: mongodb://localhost
      database: xc_cms
#配置rabbitmq
  rabbitmq:
    addresses: 192.144.198.148:5672
    virtual-host: /
    username: guest
    password: guest
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        # 配置了手工签收
        acknowledge-mode: manual
        # 最小的消费者数量.
        concurrency: 1
        # 最大的消费者数量.
        max-concurrency: 10
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 1200
  cloud:
    nacos:
      discovery:
        server-addr: 192.144.198.148:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
xuecheng:
  mq:
    queuename: queue_cms_postpage_01
    # 路由Key为门户站点ID
    routingkey: 5a751fab6abb5044e0d19ea1
    exchangename: ex_routing_cms_postpage