server:
  port: 8080
spring:
  application:
    name: freemaker-test
  data:
    mongodb:
      # 副本集的连接字符串
        uri: mongodb://114.55.37.2:27017,114.55.37.2:27018,114.55.37.2:27019/test?connect=replicaSet&slaveOk=true&replicaSet=myrs


  freemarker:
    cache: false
    settings:
      template_update_delay: 0  #检查模板更新延迟时间 为0则当数据模板改变时立即刷新
